'use strict';
const KEY='phoenixFinalV3';
const base={coins:0,totalCoins:0,xp:0,totalXP:0,level:1,highestLevel:1,energy:100,maxEnergy:100,taps:0,tapPower:1,combo:1,highestCombo:1,rewardsClaimed:0,achievementsUnlocked:0,playerName:'Phoenix Player',streak:0,lastStreakClaim:'',dailyClaimed:'',referralCount:0,referralCoins:0,referralClaimed:false,coinBoostUntil:0,xpBoostUntil:0,coinMissionClaimed:false,tapMissionClaimed:false,xpMissionClaimed:false,tapUpgradeLevel:0,energyUpgradeLevel:0,xpUpgradeLevel:0,claimedAchievements:{}};
let s=load(),comboTimer,msgTimer;
const $=id=>document.getElementById(id), set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
function load(){try{return {...base,...JSON.parse(localStorage.getItem(KEY)||'null')}}catch{return {...base}}}
function save(){localStorage.setItem(KEY,JSON.stringify(s))}
function day(){const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function need(){return s.level*100}
function add(n){s.coins+=n;s.totalCoins+=n}
function spend(n){if(s.coins<n){msg('🪙 Not enough coins!');return false}s.coins-=n;return true}
function msg(t){let e=$('phoenixMessage');if(!e){e=document.createElement('div');e.id='phoenixMessage';Object.assign(e.style,{position:'fixed',left:'50%',bottom:'25px',transform:'translateX(-50%)',background:'#202b3d',padding:'13px 18px',borderRadius:'13px',zIndex:20000,fontWeight:'bold'});document.body.appendChild(e)}clearTimeout(msgTimer);e.textContent=t;e.style.opacity=1;msgTimer=setTimeout(()=>e.style.opacity=0,2400)}
function ui(){set('level',`⭐ Level: ${s.level}`);set('xp',`✨ XP: ${s.xp} / ${need()}`);set('energy',`⚡ Energy: ${s.energy} / ${s.maxEnergy}`);set('coins',`🪙 Coins: ${s.coins}`);set('combo',`🔥 Combo: x${s.combo}`);set('profileLevel',s.level);set('profileCoins',s.coins);set('profileTaps',s.taps);set('playerName',s.playerName);set('statTotalCoins',s.totalCoins);set('statTotalTaps',s.taps);set('statHighestCombo','x'+s.highestCombo);set('statHighestLevel',s.highestLevel);set('statRewards',s.rewardsClaimed);set('statAchievements',s.achievementsUnlocked);$('energyFill').style.width=Math.max(0,s.energy/s.maxEnergy*100)+'%';missions();streak();boosts();achievements();leader()}
function tap(){if(s.energy<1)return msg('⚡ No Energy!');let c=s.tapPower*(Date.now()<s.coinBoostUntil?2:1),x=Date.now()<s.xpBoostUntil?2:1;s.energy--;s.taps++;s.coins+=c;s.totalCoins+=c;s.xp+=x;s.totalXP+=x;s.combo++;s.highestCombo=Math.max(s.highestCombo,s.combo);effect(c);level();check();ui();save()}
function effect(n){for(const id of ['plusOne','coinFly']){const e=$(id);e.textContent='🪙 +'+n;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}}
function level(){let up=0;while(s.xp>=need()){s.xp-=need();s.level++;s.highestLevel=Math.max(s.highestLevel,s.level);s.energy=s.maxEnergy;add(100);up++}if(up){set('newLevelText','⭐ Level '+s.level);$('levelUpPopup').classList.add('show')}}
function missions(){const a=Math.min(s.totalCoins,1000),b=Math.min(s.taps,100),c=Math.min(s.totalXP,500);[['coinMissionText',a,1000],['tapMissionText',b,100],['xpMissionText',c,500]].forEach(x=>{set(x[0],`${x[1]} / ${x[2]}`);const id=x[0].replace('Text','Fill');$(id).style.width=x[1]/x[2]*100+'%'}) ;mission('coinMissionReward',a>=1000,s.coinMissionClaimed,'coin');mission('tapMissionReward',b>=100,s.tapMissionClaimed,'tap');mission('xpMissionReward',c>=500,s.xpMissionClaimed,'xp')}
function mission(id,done,claimed,type){const e=$(id);e.disabled=!done||claimed;e.textContent=claimed?'✅ CLAIMED':done?'🎁 CLAIM REWARD':({coin:'🎁 Claim 200 Coins',tap:'🎁 Claim 300 Coins',xp:'🎁 Claim 500 Coins'})[type]}
function claimMission(t){const q={coin:[s.totalCoins>=1000,'coinMissionClaimed',200],tap:[s.taps>=100,'tapMissionClaimed',300],xp:[s.totalXP>=500,'xpMissionClaimed',500]}[t];if(!q[0]||s[q[1]])return;s[q[1]]=true;add(q[2]);s.rewardsClaimed++;msg('🎁 +'+q[2]+' Coins!');check();ui();save()}
function daily(){if(s.dailyClaimed===day())return msg('🎁 Already claimed!');add(500);s.dailyClaimed=day();s.rewardsClaimed++;msg('🎁 +500 Coins!');check();ui();save()}
const sr=[0,100,150,250,350,500,750,2000];
function streak(){set('streakStatus',`🔥 Current Streak: ${s.streak} Days`);document.querySelectorAll('.streak-day').forEach(e=>{let n=+e.dataset.day;e.classList.remove('current-day','completed-day');if(n<=s.streak)e.classList.add('completed-day');if(n===s.streak+1)e.classList.add('current-day')});$('claimStreak').disabled=s.lastStreakClaim===day()}
function claimStreak(){if(s.lastStreakClaim===day())return msg('🔥 Already claimed today!');s.streak=s.streak>=7?1:s.streak+1;s.lastStreakClaim=day();add(sr[s.streak]);s.rewardsClaimed++;if(s.streak===7){$('megaPopup').classList.add('show');confetti()}else msg(`🔥 Day ${s.streak}: +${sr[s.streak]} Coins!`);ui();save()}
function copy(){let t=$('referralCode').textContent;if(navigator.clipboard)navigator.clipboard.writeText(t).then(()=>msg('📋 Copied!')).catch(()=>fallback(t));else fallback(t)}
function fallback(t){let a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();try{document.execCommand('copy');msg('📋 Copied!')}catch{msg('❌ Copy failed')}a.remove()}
function referral(){if(s.referralClaimed)return msg('🎁 Already claimed!');if(!s.referralCount)return msg('👥 Invite at least 1 friend!');let n=s.referralCount*100;add(n);s.referralCoins+=n;s.referralClaimed=true;s.rewardsClaimed++;msg('👥 +'+n+' Referral Coins!');ui();save()}
function boosts(){let a=[];if(Date.now()<s.coinBoostUntil)a.push('🔥 2× Coins');if(Date.now()<s.xpBoostUntil)a.push('✨ 2× XP');set('boostStatus',a.length?'🚀 Active: '+a.join(' • '):'🚀 No active boost')}
function buy(type){let [cost,action]=type==='coin'?[500,()=>s.coinBoostUntil=Date.now()+300000]:type==='energy'?[300,()=>s.energy=s.maxEnergy]:[500,()=>s.xpBoostUntil=Date.now()+300000];if(!spend(cost))return;action();msg(type==='coin'?'🔥 2× Coins active!':type==='energy'?'⚡ Energy restored!':'✨ 2× XP active!');ui();save()}
function shop(type){let [cost,action]=type==='tap'?[100*(s.tapUpgradeLevel+1),()=>{s.tapPower++;s.tapUpgradeLevel++}]:type==='energy'?[250*(s.energyUpgradeLevel+1),()=>{s.maxEnergy+=25;s.energy=s.maxEnergy;s.energyUpgradeLevel++}]:[500*(s.xpUpgradeLevel+1),()=>{s.xp+=50;s.totalXP+=50;s.xpUpgradeLevel++;level()}];if(!spend(cost))return;action();ui();save()}
const ach={achievementCombo:['🔥 Combo King',200,()=>s.highestCombo>=10],achievementCoins10K:['💰 Phoenix Millionaire',1000,()=>s.totalCoins>=10000],achievementLevel25:['🚀 Phoenix Legend',2000,()=>s.highestLevel>=25],achievement1000:['🪙 Coin Hunter',200,()=>s.totalCoins>=1000],achievementLevel10:['⭐ Rising Phoenix',500,()=>s.highestLevel>=10],achievementTap100:['🔥 Tap Master',300,()=>s.taps>=100]};
function check(){for(const [id,a] of Object.entries(ach))if(a[2]()&&!s.claimedAchievements[id]){s.claimedAchievements[id]=true;add(a[1]);s.rewardsClaimed++;s.achievementsUnlocked++;set('achievementPopupName',a[0]);set('achievementPopupReward','🎁 +'+a[1]+' Coins');$('achievementPopup').classList.add('show');confetti()}}
function achievements(){for(const id of Object.keys(ach)){let e=$(id);if(e){let u=!!s.claimedAchievements[id];e.classList.toggle('unlocked',u);e.querySelector('span').textContent=u?'✅ Unlocked':'🔒 Locked'}}}
function leader(){let l=[['🔥 Phoenix Master',25000],['⚡ Fire Lord',18000],['🐦‍🔥 Flame King',12000],[s.playerName,s.totalCoins]].sort((a,b)=>b[1]-a[1]);$('leaderboardList').innerHTML=l.map((x,i)=>`<div class="player-row"><b>#${i+1}</b><span class="player-name">${safe(x[0])}</span><span class="player-score">🪙 ${x[1]}</span></div>`).join('')}
function safe(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function confetti(){let c=$('confettiContainer');c.innerHTML='';for(let i=0;i<60;i++){let e=document.createElement('i');e.className='confetti';e.style.left=Math.random()*100+'%';e.style.background=`hsl(${Math.random()*360},90%,60%)`;e.style.animationDelay=Math.random()*1+'s';c.appendChild(e)}setTimeout(()=>c.innerHTML='',3500)}
function close(id){$(id)?.classList.remove('show')}
document.addEventListener('DOMContentLoaded',()=>{ $('tapButton').onclick=()=>{tap();clearTimeout(comboTimer);comboTimer=setTimeout(()=>{s.combo=1;ui();save()},2500)};$('dailyReward').onclick=daily;$('claimStreak').onclick=claimStreak;$('coinMissionReward').onclick=()=>claimMission('coin');$('tapMissionReward').onclick=()=>claimMission('tap');$('xpMissionReward').onclick=()=>claimMission('xp');$('copyReferral').onclick=copy;$('claimReferral').onclick=referral;$('coinBoost').onclick=()=>buy('coin');$('energyBoost').onclick=()=>buy('energy');$('xpBoost').onclick=()=>buy('xp');$('tapUpgrade').onclick=()=>shop('tap');$('energyUpgrade').onclick=()=>shop('energy');$('xpUpgrade').onclick=()=>shop('xp');$('changeName').onclick=()=>{let n=prompt('Enter your Phoenix name:',s.playerName)?.trim().slice(0,20);if(n){s.playerName=n;ui();save()}};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));ui();check();ui();setInterval(()=>{if(s.energy<s.maxEnergy)s.energy++;boosts();streak();save()},1000)});

